site_name: JD Consultores – Documentação Técnica
site_description: Documentação técnica e arquitetural dos serviços JD
site_author: Lucas Lopes

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.details
  - pymdownx.highlight

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

nav:
  - Home: index.md
  - Arquitetura:
      - Visão Geral: arquitetura/index.md
      - Inclusão de Título: arquitetura/fluxo-inclusao-titulo.md
      - Template de Arquitetura: arquitetura/template-arquitetura-oficial.md
  - APIs:
      - Visão Geral: apis/index.md
  - Runbooks:
      - Visão Geral: runbooks/index.md
